WIP Implement Optional Private Keys
ngoduykhanh/wireguard-ui pull request #161
Opened 2022-02-22 16:15 UTC by ferrine

Address #160

2022-02-22 18:39 UTC, ferrine commented
Ready for review

2022-02-22 19:54 UTC, SomeoneSerge requested changes
Private keys seem to be a part of the persisted state, but I cannot see how their presence reflects in GUI, or how are they ever accessed for anything after the user has been set up.

- [ ] Is there still any need for storing the private key at all?
- [ ] When the private key is persisted, consider making this explicit for the user: maybe a red "Forget private key" button

2022-02-22 19:54 UTC, SomeoneSerge commented on templates/base.html
> +                                <label for="client_public_key" class="control-label">
`client_preshared_key`?

2022-02-22 21:05 UTC, ferrine commented on templates/base.html
> +                                <label for="client_public_key" class="control-label">
What do you mean?

2022-02-22 21:08 UTC, ferrine commented
> Private keys seem to be a part of the persisted state, but I cannot see how their presence reflects in GUI, or how are they ever accessed for anything after the user has been set up.
> 
> * [ ]  Is there still any need for storing the private key at all?
> * [ ]  When the private key is persisted, consider making this explicit for the user: maybe a red "Forget private key" button

* Private key is used to include in email config
* Not storing private key at all means we can't send client config (if he doesn't share public key first)
* Like the idea to add a button, but not as a part of this PR

2022-02-22 21:11 UTC, ferrine commented on templates/base.html
> +                                <label for="client_public_key" class="control-label">
Got ot

2022-02-22 21:31 UTC, SomeoneSerge commented
> Like the idea to add a button, but not as a part of this PR

With this PR, the private key becomes `Maybe String` rather than `String`. This rather should reflect in the GUI

> Private key is used to include in email config

Oh

2022-02-23 07:07 UTC, ferrine commented
@ngoduykhanh can you please have a look?

2022-02-26 12:16 UTC, ngoduykhanh commented
@ferrine thank you for your contribution. The code changes look good to me but I have a few concerns/comments:
- What is the purpose of this feature? Is it for importing the existing WG config? If so, how do we manage the private key? We need it to generate a proper QR code/config file.
- I see you use `ParseKey` to validate the public keys and preshared keys. How about validating the duplication? We should not allow importing a public key that already exists. 
- [UI] Since the **Public Key** and **Preshared Key** are optional, I think we should adjust the form to hide them by default (using Collapse for example) because it is a bit long now.

2022-03-13 12:27 UTC, ferrine commented
@ngoduykhanh 
The only feature I decided not to implement is 
> check QR code creation, raise an error if the private key is missing
It still generates the QR code but the config is incomplete (it was supposed to be so). Incomplete config is an expected behavior so I treat this as a feature.

2022-03-13 13:16 UTC, ferrine commented
This is a simple way to tell there is no QR
<img width="541" alt="image" src="https://user-images.githubusercontent.com/11705326/158061130-d83e5d69-d879-48dd-bda4-23cd3efb72a9.png">

2022-03-13 13:51 UTC, ferrine commented
an updated version disables Scan button
<img width="263" alt="image" src="https://user-images.githubusercontent.com/11705326/158062648-107681be-a919-4539-bb12-affa4ac755fe.png">

2022-03-13 14:49 UTC, ngoduykhanh requested changes
Thanks @ferrine for addressing the issues. I have one more comment below. Other changes look good.

2022-03-13 14:49 UTC, ngoduykhanh commented on templates/clients.html
> +            <img id="qr_code" class="w-100" style="image-rendering: pixelated;" src="" alt="QR code not available" />
Can you revert this line? It will be always `QR code not available` even the QR code is available.

2022-03-13 15:44 UTC, ferrine commented
Done

2022-03-13 16:33 UTC, ngoduykhanh approved these changes

2022-03-13 16:33 UTC, merged