Fix for fwmark
ngoduykhanh/wireguard-ui pull request #279
Opened 2022-12-21 20:28 UTC by systemcrash

Evidently, wireguard's (use of) fwmark is not well understood. In short, it determines which routing table to use for a tunnel's packets.

Adding a fwmark to a roadwarrior client config won't do anything to the actual packets sent to a peer: Packets do not get marked.

The wireguard client thinks a QRCode with `FwMark = ...` in it is invalid.

FwMark is now excluded from client configs (but is written to the server config /etc/wireguard/wgX.conf).

Potential breaking change of `WGUI_FORWARD_MARK` to `WGUI_FIREWALL_MARK`

But this has the effect of making users eventually notice that it probably does not do what they want/think.

See:
https://ro-che.info/articles/2021-02-27-linux-routing https://casavant.org/2020/10/10/wireguard-fwmark.html https://www.blinkenlights.ch/ccms/posts/source-based-routing/

2022-12-26 09:11 UTC, ngoduykhanh requested changes

2022-12-26 09:11 UTC, ngoduykhanh commented on util/util.go
> +		//firewallMark +
Where is the `firewallMark` used in the end?

2022-12-26 09:11 UTC, ngoduykhanh commented on store/jsondb/jsondb.go
> +		*/
Maybe we can just remove all commented codes if we don't need them. The same for other places

2023-02-16 12:26 UTC, systemcrash commented
ping @ngoduykhanh

2023-02-16 16:05 UTC, ngoduykhanh commented on util/util.go
> +		//firewallMark +
@systemcrash can you address my question? I don't know if I get the idea of having firewallMark since it is not used anywhere in the config file.

2023-03-15 20:37 UTC, merged

2023-05-28 01:22 UTC, PizzaProgram commented
I've just installed latest `v0.4.0` and this is still happening.  
When I click Download, the client is containing a line:
`fwmark = ...`