Telegram support
ngoduykhanh/wireguard-ui pull request #488
Opened 2023-11-18 13:37 UTC by 0xCA

# Telegram support
![image](https://github.com/ngoduykhanh/wireguard-ui/assets/11984323/53020d5e-c6cc-4ae3-b5f8-23ead259c9cf)
> Telegram userid settings and config send button
> Userid setting is moved to a separate collapsible section

## Reason
- In short, convenience and time saving
- Mainly intended for quick effortless distribution, especially for large servers and mass config updates

## Details
- You can assign one user id or group id to each client config.
- Each telegram userid can be assigned to multiple configs, so one user can have multiple configs.
- You can search by userid on the clients page.
- There is a configurable _global_ flood wait. It applies to both manual config push and a user request. 1h default.
- I used dependency injection to avoid circular dependencies with util.
- There is an in-memory cache of `tg userid -> client ids` correspondence to avoid heavy db usage.
- Pre-generated QR codes are kinda low res for telegram. So I generate 512x512 images each time they are needed. 

## Config request
![image](https://github.com/ngoduykhanh/wireguard-ui/assets/11984323/f86173b9-d51d-4173-86ac-31a00d285535)
> Send any message to the bot to get **all** the configs associated with your userid
- If config requests are disabled, bot module will not listen to updates. You can have a separate server handling the incoming messages without conflicts.
- If you have multiple configs assigned to you, they are sent with a 2s delay between them, to avoid hitting bot API limits.
- If there are no configs assigned, flood wait is still applied to avoid bot overload.

## Configuration
| Variable                      | Description                                                                                                                                                  | Default                            |
| ----------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | ---------------------------------- |
| `TELEGRAM_TOKEN`              | Telegram bot token for distributing configs to clients                                                                                                       | N/A                                |
| `TELEGRAM_ALLOW_CONF_REQUEST` | Allow users to get configs from the bot by sending a message                                                                                                 | `false`                            |
| `TELEGRAM_FLOOD_WAIT`         | Time in minutes before the next conf request is processed                                                                                                    | `60`                               |

None of this configuration is saved to the database. You can change it by restarting the wgui.

# Conflicts
I tried to minimize conflicts for this branch, but they are inevitable,
#### The advised merge order:
1. #470
2. #481
3. #483
4. this

If you intend to merge all of the above, you can simplify this by merging https://github.com/0xCA/wireguard-ui/tree/umaster, where all the conflicts are already resolved.

## Future
As this repo is currently inactive, it's inconvenient to continue development from the stale master. Further development (if any) is going to be in my repo. Feel free to check and contribute.

2023-11-19 10:10 UTC, nebulosa2007 commented
Also thought about adding Telegram ID in clients settings :) For now I use Email field for filling Telegram Id and just parse json files with my own tgbot. Nothing special - it parses wgui configs and send .conf files with generated QR-code to user according his TgID.

This setup is more convenient than yours, because conf files send to user when he wants, but not when you press the button in wgui admin interface (besides user must add tgbot to contacts before, that you could send him an anything).

2023-11-30 17:16 UTC, X-UIP commented
How can update Wireguard-UI to get this ability?

2023-12-03 21:07 UTC, X-UIP commented
> @X-UIP There is no public image built from my branch. You should build it yourself. Hint: you will need to update Go version in Dockerfile. Use `golang:1.20-alpine3.17` as build and `alpine:3.17` as runtime.

excuse me! if you can create a learning! because I don't know exactly what you say! I can create and run, Wireguard UI with a docker file and special image, but your work i don't know yours!

2023-12-25 20:11 UTC, ngoduykhanh commented
Hey @0xCA, thank you for another contribution here. I guess I should touch this PR after solving #481. I've just left a comment there.
Although I am a Telegram user, I don't really see how this feature would be helpful in my daily use case. However, I am happy to merge if somebody else needs it. Let me know if you still want to continue with your contribution here or if you want to stop and keep it in your folks.

2023-12-27 08:48 UTC, ngoduykhanh commented
@0xCA fair enough. I merged the other PR. could you please resolve this PR conflict as well?

2023-12-28 19:58 UTC, ngoduykhanh requested changes
Found an issue. When the `TELEGRAM_ALLOW_CONF_REQUEST` is not set and it has `false` value by default, I cannot send the Telegram user the config. 

<img width="373" alt="telegram-req-error" src="https://github.com/ngoduykhanh/wireguard-ui/assets/6447444/25a312ca-d10d-4e3b-8823-e71f43df46ca">

When `TELEGRAM_ALLOW_CONF_REQUEST=true`, everything is fine.

2023-12-28 19:58 UTC, ngoduykhanh commented on telegram/bot.go
> +	TelegramFloodWait        int
```suggestion
	Token            string
	AllowConfRequest bool
	FloodWait        int
```

The variable name shouldn't start with package name.

2023-12-28 19:58 UTC, ngoduykhanh commented on telegram/bot.go
> +	TgBotMutex sync.RWMutex
```suggestion
	Bot      *echotron.API
	BotMutex sync.RWMutex
```

I think it is a better naming

2023-12-29 08:22 UTC, ngoduykhanh commented
Perfect! I am merging the PR. Thank you for addressing all the issues.

2023-12-29 08:22 UTC, merged

2024-01-07 13:40 UTC, PulseDiver commented
Where should I add these settings - TELEGRAM_TOKEN, TELEGRAM_ALLOW_CONF_REQUEST and TELEGRAM_FLOOD_WAIT?