Session improvements
ngoduykhanh/wireguard-ui pull request #510
Opened 2023-12-28 12:37 UTC by 0xCA

## Session improvements
### Fixed and improved
- Fixed session duration
- Use MaxAge instead of Expires
- Added cookie refresh on all pages (API calls are ignored)
- Refresh not sooner than 24h
- Do not refresh temporary sessions
- Delete cookies on logout
### Enhanced security
- Use HttpOnly and SameSite
- Auth + Encryption for cookies, based on SessionSecret, via SHA512
- Verify if the cookie is not too old and not from the future
- Verify if the user exists and unchanged
- Any change to the user logs out all _other_ sessions as a result
### Params
| Variable                      | Description                                                                                                                                                                                                                                                                         | Default                            |
|-------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------|
| `SESSION_MAX_DURATION`        | Max time in days a remembered session is refreshed and valid. Non-refreshed session is valid for 7 days max, regardless of this setting.                                                                                                                                            | 90                                 |
### Discussion
Open for discussion, please check for errors

2024-01-05 15:39 UTC, ngoduykhanh requested changes

2024-01-05 15:39 UTC, ngoduykhanh commented on handler/session.go
> +// Refresh is performet at most once per 24h
typo: `performed` instead of `performet`

2024-01-06 08:10 UTC, ngoduykhanh approved these changes

2024-01-06 08:11 UTC, merged

2025-05-19 01:37 UTC, samrocketman commented
Question: was it intended that sessions don't survive a restart?  I was expecting to preserve sessions when restarting wireguard-ui after customizing session secret env var.