Update helper.js
ngoduykhanh/wireguard-ui pull request #66
Opened 2021-05-31 12:41 UTC by catmandx

Changed download button to a tag so that it's possible to right click and copy link.

2021-08-05 18:12 UTC, ngoduykhanh requested changes

2021-08-05 18:12 UTC, ngoduykhanh commented on main.go
> +	appVersion = "v0.2.7-1"
Why setting this version?

2021-08-05 18:12 UTC, ngoduykhanh commented on prepare_assets.sh
> +# yarn install --pure-lockfile --production
Why do we remove this step?

2021-08-05 18:12 UTC, ngoduykhanh commented on yarn.lock
I don't think we need to update the this file as the package file remains the same

2021-08-05 18:12 UTC, ngoduykhanh commented on templates/base.html
> +            <strong>Copyright &copy; 2021 <a href="https://github.com/catmandx/wireguard-ui">Wireguard UI</a>.</strong> All rights
Why do you replace the original project link? :)

2021-08-05 18:13 UTC, ngoduykhanh commented on .gitignore
> +yarn.lock
They should be in the version control

2021-08-05 18:15 UTC, catmandx commented
Hey, I didn't know that additional commits would show up here with the original PR commit. Sorry for the inconvenience.

2021-11-08 02:48 UTC, catmandx commented
I have reverted the problematic commits, please review the changes to the download functionality.

2021-11-09 10:06 UTC, ngoduykhanh approved these changes
LGTM now. Merging your PR. Thanks for your contribution!

2021-11-09 10:06 UTC, merged

2022-02-05 11:54 UTC, varhub commented on handler/routes.go
> +		c.Response().Header().Set(echo.HeaderContentDisposition, fmt.Sprintf("attachment; filename=%s.conf", clientData.Client.Name))
this tiny change made my day. Thank you.